name: Terraform Plan

on: pull_request

env:
  TF_WORKSPACE: "terraform-plan-github-action"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  tf_version: "1.8.0"
  tg_version: "0.56.5"
  working_dir: '.'

jobs:
  terragrunt-terraform:
    name: Plan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
      
      - name: Format
        uses: gruntwork-io/terragrunt-action@v2
        id: fmt
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run-all fmt'
        continue-on-error: true
      
      - name: Init
        uses: gruntwork-io/terragrunt-action@v2
        id: init
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run-all init -upgrade'
      
      - name: Validate
        uses: gruntwork-io/terragrunt-action@v2
        id: validate
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'run-all validate'
